# AWS CodeBuild spec to build an Elastic Beanstalk artifact for AWS CodePipeline to deploy
version: 0.2
    
env:
   variables:
     PROJECT: ACEBackEndApp
     DOTNET_CORE_RUNTIME: 8.0

phases:   
  install:
    runtime-versions:
      dotnet: ${DOTNET_CORE_RUNTIME}
      
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore
      
  build:
    commands:
      - echo Build started on `date`
      - dotnet build -c Release
      
  post_build:
    commands:
      - echo Publish started on `date`
      - dotnet publish ACEBackEnd.csproj -c Release -r linux-x64 -o ./publish
      - cp Procfile ./build_output

artifacts:
  files:
    - '**/*'
  base-directory: ./build_output
  discard-paths: no